#!/usr/bin/env python3
"""
hide/unhide vertical tab bar by moving mouse to left edge of screen

- restores mouse to previous saved position if statefile exists
- otherwise, saves current position in ~/var/mousepark/position.dat
- then moves mouse to left edge of screen
"""
__url__     = 'https://github.com/smemsh/utilx/'
__author__  = 'Scott Mcdermott <scott@smemsh.net>'
__license__ = 'GPL-2.0'

import argparse

from sys import exit, hexversion
if hexversion < 0x030900f0: exit("minpython: %s" % hexversion)

from sys import argv, stdout, stderr, exit
from traceback import print_exc

from os.path import basename, dirname, isdir, exists
from os import (
    getenv, remove,
    chdir, makedirs,
    access, R_OK, W_OK,
    EX_OK as EXIT_SUCCESS,
    EX_SOFTWARE as EXIT_FAILURE,
)

from Xlib.display import Display
from Xlib.Xatom import CARDINAL

# TODO: Xlib.display.Display().warp_pointer
from pynput.mouse import Controller

###

def err(*args, **kwargs):
    print(*args, file=stderr, **kwargs)

def bomb(*args, **kwargs):
    err(*args, **kwargs)
    exit(EXIT_FAILURE)

###

def process_args():

    global args

    def addopt(p, flagchar, longopt, help=None, /, **kwargs):
        options = list(("-%s --%s" % (flagchar, longopt)).split())
        p.add_argument(*options, help=help, **kwargs)

    def addflag(*args, **kwargs):
        addopt(*args, action='store_true', **kwargs)

    p = argparse.ArgumentParser(
        prog            = invname,
        description     = __doc__.strip(),
        allow_abbrev    = False,
        formatter_class = argparse.RawTextHelpFormatter,
    )
    addopt  (p, 's', 'statefile', 'path to position state file')
    addflag (p, 'r', 'right', 'park cursor to right, not left')
    args = p.parse_args(args)

    return args.statefile \
        or f"{getenv('HOME')}/var/{invname}/position.dat"


def check_sanity(path):

    sdir = dirname(path)
    sfile = basename(path)

    if not exists(sdir):
        try: makedirs(sdir)
        except: bomb(f"statedir '{sdir}' creation failed")

    elif not isdir(sdir):
        bomb(f"refusing overwrite of '{sdir}' (not a directory)")

    if not access(sdir, W_OK):
        bomb(f"cannot write to statedir '{sdir}'")

    if exists(path) and not access(path, R_OK|W_OK):
        bomb(f"cannot write to statefile '{sfile}'")

    return sdir, sfile

###

def mousepark():

    statepath = process_args()
    statedir, statefile = check_sanity(statepath)

    try: chdir(statedir)
    except: bomb(f"cannot change directory to '{statedir}'")

    try:
        rootwin = display.screen(0)['root']
        propname = display.get_atom('_NET_WORKAREA')
        workarea = rootwin.get_full_property(propname, CARDINAL, 32)
        width = workarea.value[2]
        height = workarea.value[3]
    except:
        bomb("cannot determine window size")

    if exists(statefile):
        # restore and erase state
        f = open(statefile)
        x = int(f.readline())
        y = int(f.readline())
        minx = int(width / 3) + 100  # left unpark just right of 1/3
        maxx = int(width / 3) * 2 - 100  # right unpark just left of 2/3
        newx = min(x, maxx) if args.right else max(x, minx)
        mouse.position = (newx, y)
        try: remove(statefile)
        except: bomb(f"cannot remove {statepath}")

    else:
        # park and save state
        x, y = mouse.position
        f = open(statefile, 'xt')
        f.writelines([f"{i}\n" for i in (x, y)])

        # x must be a few pixels from edge for vtabs to unfurl
        margin = 5
        newx = width - margin if args.right else margin
        mouse.position = (newx, y)

        # todo: does not work for some reason, maybe look at lib code
        #display.warp_pointer(newx, y, rootwin)
        #print(f"display.warp_pointer(x: {newx}, y: {y}, rootwin: {rootwin}")

###

def main():

    if debug == 1:
        breakpoint()

    try: subprogram = globals()[invname]
    except (KeyError, TypeError):
        from inspect import trace
        if len(trace()) == 1: bomb(f"unimplemented")
        else: raise

    return subprogram()

###

if __name__ == "__main__":

    invname = basename(argv[0])
    args = argv[1:]

    from bdb import BdbQuit
    debug = int(getenv('DEBUG') or 0)
    if debug:
        import pdb
        from pprint import pp
        err('debug: enabled')

    try: mouse = Controller()
    except: bomb("cannot get mouse controller object")

    try: display = Display()
    except: bomb("cannot get display")

    try: main()
    except BdbQuit: bomb("debug: stop")
    except SystemExit: raise
    except KeyboardInterrupt: bomb("interrupted")
    except:
        print_exc(file=stderr)
        if debug: pdb.post_mortem()
        else: bomb("aborting...")
    finally: # cpython bug 55589
        try: stdout.flush()
        finally:
            try: stdout.close()
            finally:
                try: stderr.flush()
                finally: stderr.close()
