#!/usr/bin/env bash
#
# rptaskdesc
#   display current task description as a ratpoison message
#

source ~/.taskenv
declare -a tasknow=($(tasknow))
fql=${tasknow[0]}

rp echo "$(taskfield `taskuuid` description) ($fql)"
