#!/usr/bin/env bash
#
# rptmux
#   adds ratpoison keymaps to generate tmux-bound keypresses off Super modkey
#
# desc:
#   - queries running tmux for its keybinds (not needed, see todo)
#   - generates ratpoison binds off super for the unprefixed tmux key
#   - emits the keys by executing 'rpmeta' wrapper
#   - writes the sourceable ratpoison bindings to tmpfile
#   - invokes ratpoison to source the file, which adds the mappings
#
# todo:
#   - processes only 'prefix' keymap from tmux, ignores rest
#   - tmux-2.2: "list-keys and list-commands can be run without starting the
#     tmux server" so use that, i.e. no longer need to run within tmux
#
# note:
#   old way we did this was to actually execute the tmux command; we do
#   not do that anymore because it doesn't know which session to target,
#   so if we have multiple clients attached to different sessions, only
#   the first one will get it, which would require that we look up the
#   terminal -> pid -> client -> session mapping, which is more
#   difficult, so we just emit a keypress instead (much easier) which
#   works with whatever client we are connected with at present moment
#
# stat:
#   - used by author
#   - please notify if using
#
# scott@smemsh.net
# http://smemsh.net/src/ratutils/
# http://spdx.org/licenses/GPL-2.0
#
##############################################################################

# don't expand pathnames in this script, interacts poorly with emit_mapping()
set -f

# ratpoison keymap to enter the bindings into
#
rpmap=top

# name of "ratpoison -c meta" command wrapper
#
rpmetacmd=rpmeta

# string prefix to insert before the bound keysym, eg a
# ratpoison modifier (in this case we prefix 'Super' key)
# todo: specify it, either as arg, env, rcfile
#
rppfx='s-'

# this is the '-T <map>' tmux map that we rebind using the
# Super prefix; any tmux keys in other maps (ie root map) will
# be ignored for the time being
#
tmuxmap='prefix'

# prefix we want to emit (give to rpmeta), this should
# correspond to the tmux prefix in ratpoison parlance (todo:
# query it from tmux instead of having to specify it here)
#
tmuxpfx='C-q'

##############################################################################

#
# tmux -> xorg
# key lookup table
#
# mappings created manually, starting from:
#   xmodmap -pke \
#   | awk '{for (i = 4; i < NF; i++) printf("%s\n", $i)}' \
#   | sort -u \
#   | grep -v -e brokenbar -e plusminus \
#   | grep -E '\<[a-z]{2,}$'
#
add_maps_puncts ()
{
	charmap['&']=ampersand
	charmap["'"]=apostrophe
	charmap['^']=asciicircum
	charmap['~']=asciitilde
	charmap['*']=asterisk
	charmap['@']=at
	charmap['\']=backslash
	charmap['|']=bar
	charmap['{']=braceleft
	charmap['}']=braceright
	charmap['[']=bracketleft
	charmap[']']=bracketright
	charmap[':']=colon
	charmap[',']=comma
	charmap['$']=dollar
	charmap['=']=equal
	charmap['!']=exclam
	charmap['`']=grave
	charmap['>']=greater
	charmap['<']=less
	charmap['-']=minus
	charmap['#']=numbersign
	charmap['(']=parenleft
	charmap[')']=parenright
	charmap['%']=percent
	charmap['.']=period
	charmap['+']=plus
	charmap['?']=question
	charmap['"']=quotedbl
	charmap[';']=semicolon
	charmap['/']=slash
	charmap['_']=underscore
}

# map also the rest of the normal keyboard keys
# (just ordinary characters bound to themselves)
#
add_maps_alnums ()
{
	local c

	for c in {0..9} {a..z} {A..Z}; do
		charmap[$c]=$c; done
}

##############################################################################

emit_mapping ()
{
	local key
	local cmd
	local mapped

	# eat the initial 'bind-key' from tmux list-keys
	shift

	# first arg may be a 'bind-key' argument (like '-r')
	#   which we do not support, only simple binds, no flags
	#   supported
	# UPDATE: in v2.1, tmux adds '-T <keymap>' to every
	#   command, we disregard this from the input by
	#   shifting past it (and only keymap we want to
	#   interact with at all is '-T prefix', the rest we
	#   ignore altogether)
	# TODO: if ever there is "-T map -r" instead of "-r -T
	#   map" this would break... can this happen?)
	#
	if [[ "$1 $2" == "-T $tmuxmap" ]]
	then key=$3
	else return; fi

	# we only handle single-char mappings; in our tmuxrc,
	# only a couple rarely-used binds are chords or
	# symbolics, so those mappings can be skipped for now;
	#
	# TODO: can ratpoison even emit eg control-x ? we should handle
	# arbitrary key sequences if so
	#
	((${#key} > 1)) &&
		continue

	# new way calls our 'rpmeta' command, which simply emits the key
	#
	mapped=${charmap[$key]}
	execmd="$rpmetacmd $tmuxpfx $mapped"
	echo "echo definekey $rpmap $rppfx$mapped exec $execmd"
	echo "definekey $rpmap $rppfx$mapped exec $execmd"
	echo "time"
}

emit_mappings ()
{
	local line

	tmux list-keys \
	| while read line; do
		emit_mapping $line; done
}

##############################################################################

# generate the mappings and source them into ratpoison
#
main ()
{
	local tmpfile
	declare -A charmap

	add_maps_puncts
	add_maps_alnums

	tmpfile=`mktemp`
	emit_mappings >| $tmpfile
	ratpoison -c "source $tmpfile"
	rm $tmpfile
}

main "$@"
