#!/bin/sh

# add display to sockpath, we sometimes run X on more than one VT
export RXVT_SOCKET=$HOME/.urxvt/urxvtd-${HOSTNAME:-$(hostname)}$DISPLAY

for try in 1 2 3; do
	/usr/bin/urxvtc &>/dev/null && exit
	[ $? -eq 2 ] && urxvtd -q -f -o
	sleep 0.1
done

echo "no clean status from urxvtc after several tries, aborting" >&2
false
