#!/bin/bash
#
# xflashscreen
#   flashes xorg screen $1 times for $2 ms
#
# args:
#   - $1 inversions (default 4)
#   - $2 ms to sleep between 2 successive inversions (default 40)
#
# deps:
#   - https://github.com/smemsh/utilx/ xinvert
#
# scott@smemsh.net
# https://github.com/smemsh/utilx/
# https://spdx.org/licenses/GPL-2.0
#
##############################################################################

msleep ()
{
	sleep $(bc <<< "0.001 * $1")
}

main ()
{
	local i iters sleep

	iters=$((${1:-4} * 2)) # invert twice to return to normal
	sleep=$((${2:-40} / 2)) # sleep ms between full cycles (two inversions)

	for ((i = 0; i < iters; i++)); do
		DISPLAY=${DISPLAY:-':0'} xinvert
		msleep $sleep
	done
}

main "$@"
